// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/api/aline.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_REGISTER   MessageType = 0
	MessageType_UNREGISTER MessageType = 1
	MessageType_HEARTBEAT  MessageType = 2
	MessageType_EXECUTE    MessageType = 3
	MessageType_CANCEL     MessageType = 4
	MessageType_RESULT     MessageType = 5
	MessageType_LOG        MessageType = 6
	MessageType_ERROR      MessageType = 7
	MessageType_FILE       MessageType = 8
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "REGISTER",
		1: "UNREGISTER",
		2: "HEARTBEAT",
		3: "EXECUTE",
		4: "CANCEL",
		5: "RESULT",
		6: "LOG",
		7: "ERROR",
		8: "FILE",
	}
	MessageType_value = map[string]int32{
		"REGISTER":   0,
		"UNREGISTER": 1,
		"HEARTBEAT":  2,
		"EXECUTE":    3,
		"CANCEL":     4,
		"RESULT":     5,
		"LOG":        6,
		"ERROR":      7,
		"FILE":       8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_api_aline_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_grpc_api_aline_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_api_aline_proto_rawDescGZIP(), []int{0}
}

type AlineMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 1: register 客户端发的注册
	// 2: offline 客户端发的注销
	// 3: heartbeat 客户端发的心跳
	// 4: execute 服务端发的执行命令
	// 5: cancel 服务端发的取消执行命令
	// 6: executeResultNotify 客户端发的执行结果通知
	// 7: log 客户端发的日志
	// 8: 错误
	// 9: 文件
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=api.MessageType" json:"type,omitempty"`
	// registry
	Name    string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address string      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ExecReq *ExecuteReq `protobuf:"bytes,4,opt,name=execReq,proto3" json:"execReq,omitempty"`
	// execute result
	Result *ExecuteResult `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	// log
	Log   string `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	File  *File  `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *AlineMessage) Reset() {
	*x = AlineMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_aline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlineMessage) ProtoMessage() {}

func (x *AlineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_aline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlineMessage.ProtoReflect.Descriptor instead.
func (*AlineMessage) Descriptor() ([]byte, []int) {
	return file_grpc_api_aline_proto_rawDescGZIP(), []int{0}
}

func (x *AlineMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_REGISTER
}

func (x *AlineMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlineMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AlineMessage) GetExecReq() *ExecuteReq {
	if x != nil {
		return x.ExecReq
	}
	return nil
}

func (x *AlineMessage) GetResult() *ExecuteResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AlineMessage) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *AlineMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AlineMessage) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type ExecuteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// pipeline file
	PipelineFile string `protobuf:"bytes,2,opt,name=pipelineFile,proto3" json:"pipelineFile,omitempty"`
	// job exec id
	JobDetailId int64 `protobuf:"varint,3,opt,name=jobDetailId,proto3" json:"jobDetailId,omitempty"`
}

func (x *ExecuteReq) Reset() {
	*x = ExecuteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_aline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReq) ProtoMessage() {}

func (x *ExecuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_aline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReq.ProtoReflect.Descriptor instead.
func (*ExecuteReq) Descriptor() ([]byte, []int) {
	return file_grpc_api_aline_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteReq) GetPipelineFile() string {
	if x != nil {
		return x.PipelineFile
	}
	return ""
}

func (x *ExecuteReq) GetJobDetailId() int64 {
	if x != nil {
		return x.JobDetailId
	}
	return 0
}

type ExecuteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName   string `protobuf:"bytes,1,opt,name=jobName,proto3" json:"jobName,omitempty"`
	JobID     int64  `protobuf:"varint,2,opt,name=jobID,proto3" json:"jobID,omitempty"`
	JobStatus int64  `protobuf:"varint,3,opt,name=jobStatus,proto3" json:"jobStatus,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_aline_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_aline_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_grpc_api_aline_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResult) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ExecuteResult) GetJobID() int64 {
	if x != nil {
		return x.JobID
	}
	return 0
}

func (x *ExecuteResult) GetJobStatus() int64 {
	if x != nil {
		return x.JobStatus
	}
	return 0
}

func (x *ExecuteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_aline_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_aline_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_grpc_api_aline_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_api_aline_proto protoreflect.FileDescriptor

var file_grpc_api_aline_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x80, 0x02, 0x0a, 0x0c,
	0x41, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x29, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x52, 0x07, 0x65, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x1d, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x66,
	0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x7d, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45,
	0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x4e, 0x52, 0x45,
	0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52,
	0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x45, 0x43, 0x55,
	0x54, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03,
	0x4c, 0x4f, 0x47, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x07,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x08, 0x32, 0x43, 0x0a, 0x08, 0x41, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x50, 0x43, 0x12, 0x37, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x6e, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x69, 0x6e, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x69,
	0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x3b, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x68, 0x61,
	0x6d, 0x73, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x61, 0x6c, 0x69,
	0x6e, 0x65, 0x42, 0x0a, 0x41, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x0a, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_api_aline_proto_rawDescOnce sync.Once
	file_grpc_api_aline_proto_rawDescData = file_grpc_api_aline_proto_rawDesc
)

func file_grpc_api_aline_proto_rawDescGZIP() []byte {
	file_grpc_api_aline_proto_rawDescOnce.Do(func() {
		file_grpc_api_aline_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_api_aline_proto_rawDescData)
	})
	return file_grpc_api_aline_proto_rawDescData
}

var file_grpc_api_aline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_api_aline_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_api_aline_proto_goTypes = []interface{}{
	(MessageType)(0),      // 0: api.MessageType
	(*AlineMessage)(nil),  // 1: api.AlineMessage
	(*ExecuteReq)(nil),    // 2: api.ExecuteReq
	(*ExecuteResult)(nil), // 3: api.ExecuteResult
	(*File)(nil),          // 4: api.File
}
var file_grpc_api_aline_proto_depIdxs = []int32{
	0, // 0: api.AlineMessage.type:type_name -> api.MessageType
	2, // 1: api.AlineMessage.execReq:type_name -> api.ExecuteReq
	3, // 2: api.AlineMessage.result:type_name -> api.ExecuteResult
	4, // 3: api.AlineMessage.file:type_name -> api.File
	1, // 4: api.AlineRPC.AlineChat:input_type -> api.AlineMessage
	1, // 5: api.AlineRPC.AlineChat:output_type -> api.AlineMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_api_aline_proto_init() }
func file_grpc_api_aline_proto_init() {
	if File_grpc_api_aline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_api_aline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlineMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_api_aline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_api_aline_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_api_aline_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_api_aline_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_api_aline_proto_goTypes,
		DependencyIndexes: file_grpc_api_aline_proto_depIdxs,
		EnumInfos:         file_grpc_api_aline_proto_enumTypes,
		MessageInfos:      file_grpc_api_aline_proto_msgTypes,
	}.Build()
	File_grpc_api_aline_proto = out.File
	file_grpc_api_aline_proto_rawDesc = nil
	file_grpc_api_aline_proto_goTypes = nil
	file_grpc_api_aline_proto_depIdxs = nil
}
